### ISSUE TITLE
Зачем нужен этот файл?

### ISSUE THREAD

**Issue by AlphaBeth** [Drukhary/web-lab3#1]
https://github.com/Drukhary/web-lab3/blob/b0aa2859231d5e37412cd97c7973feee62e4ce3a/src/main/resources/META-INF/persistence.xml#L1

**Comment by Drukhary** [comment]
Понял ошибку, удалил. 
Действительно не нужен. 
P.s Изначально я его добавил потому, что использовал такой гайд.
