### ISSUE TITLE
Сделать управляемым классом (ManagedBean) без статических методов

### ISSUE THREAD

**Issue by AlphaBeth** [Drukhary/web-lab3#2]
https://github.com/Drukhary/web-lab3/blob/b0aa2859231d5e37412cd97c7973feee62e4ce3a/src/main/java/drukhary/web/laba3/util/ElementInfoDAO.java#L9

**Comment by Drukhary** [comment]
Сделано.
Теперь я в этот класс поместил datasource и сделал его управляемым компонентом
