### ISSUE TITLE
Пользователь должен получить сообщение об ошибке, а не пустой список, при ошибке в работе БД

### ISSUE THREAD

**Issue by AlphaBeth** [Drukhary/web-lab3#5]
https://github.com/Drukhary/web-lab3/blob/b0aa2859231d5e37412cd97c7973feee62e4ce3a/src/main/java/drukhary/web/laba3/util/ElementInfoDAO.java#L48

**Comment by Drukhary** [comment]
Исправлено.
Теперь клиенту выводится красивое сообщение об ошибке(дефолтное содержание сообщения)
![image](https://user-images.githubusercontent.com/57765637/115159768-659c8c00-a09d-11eb-87fc-408be82c572d.png)
